name: first workflow
on:
  push: 
      branches:
        - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: print a welcome msg
        run: echo "Welcome to our first Github Actions Workflows"

      - name: checkout repository
        uses: actions/checkout@6.0.2

      - name: list repo files
        run: ls -la
